### ISSUE TITLE
feat(auth): allow confirming account deletion

### ISSUE THREAD

**Issue by insertish** [revoltchat/frontend#201]
Route needs to be added to auth routes.

https://github.com/revoltchat/revite/blob/d55d86aa3cb5cd0b5b29646b499dac5b16f20c1e/src/pages/login/ConfirmDelete.tsx#L16

**Comment by sabs21** [comment]
By confirming account deletion, do you mean something more than what's currently being done when you click 'Delete Account' in the user settings? It seems like confirmation exists already
![image](https://github.com/user-attachments/assets/c58a10c9-9372-4511-8be9-11861d285e40)

**Comment by insertish** [comment]
The `/login/...` route that takes a token and confirms the account should be deleted.
(from the email sent to user when they request deletion)
