### ISSUE TITLE
feat(composition): implement channel, user, emoji auto complete

### ISSUE THREAD

**Issue by insertish** [revoltchat/frontend#224]
- Channels: any in **current server**
- Users: any in **current channel** (or global if **no channel specified**)
- Emoji: **any known emoji**

  Note: shortcodes must be converted to unicode

**Comment by sharkaccino** [comment]
should this still be open? seems to be fully implemented already (although rather annoyingly, tab selection is still missing)

**Comment by insertish** [comment]
I suppose this just needs tab keybind for parity then it's done.
