### ISSUE TITLE
bug: pressing enter on either username or password field on login screen just returns back to the landing screen

### ISSUE THREAD

**Issue by searinminecraft** [revoltchat/frontend#262]
### What happened?

The title says so. I expected it to for example, if I press enter on the username field, it goes to the password field, press enter on password field, it logs in, just like the old client did. On the video though i jumped from the username field to the password field by using the tab key.

https://github.com/revoltchat/frontend/assets/114207889/5de8e48f-bf22-4684-94e3-de9594702872

**Comment by joelepore** [comment]
this happened with the old UI and is now fixed

**Comment by insertish** [comment]
Appears to be working currently
