### ISSUE TITLE
feature request: Discord-like voice chat UX

### ISSUE THREAD

**Issue by candroid-man** [revoltchat/frontend#265]
### What do you want to see?

I would love to see something like this rather than the current system where you click on the voice chat, and then click the call button. 

![image](https://github.com/revoltchat/desktop/assets/51019003/e68e860c-5c8b-439e-bddf-8dbb4075b0a1)

I think Discord nailed it with the general UX ignoring all of the useless stuff in it now, it's just that Discord is a privacy nightmare and would much rather use Revolt. I'm thinking that this would be a reason for my friends to switch over (as stupid as that may sound).

**Comment by nholloh** [comment]
I second this. I am currently looking for a discord alternative to be self-hosted for our company, to facilitate office-like communication even when working from remote. We cannot use discord due to privacy concerns as well.

**Comment by insertish** [comment]
https://github.com/revoltchat/vortex/issues/30
