### ISSUE TITLE
bug: hcaptcha is unsolvable

### ISSUE THREAD

**Issue by avarner9** [revoltchat/frontend#282]
### What happened?

The frontend at https://app.revolt.chat/login/create requires solving an hcaptcha puzzle.

I can't solve hcaptcha to sign up for an account, because I'm not willing to train an AI that will probably make my life worse.

hcaptcha has an "accessibility" system which requires that you provide to them an email address, enable third party cookies, and disable anti-fingerprint features. Notably, their accessibility sign up page seems to extract a large amount of canvas data for fingerprinting. I'm not willing to disable anti-fingerprinting.

**Comment by insertish** [comment]
Unless if you have suggestions for alternatives, there isn't anything we can do for you here.
NB. I have floated building a custom captcha solution but currently we don't have the resoucres for that.

**Comment by nlutterman** [comment]
Just out of curiosity, I took a look. Altcha looks to be a possibly good alternative.

https://github.com/altcha-org/altcha

MIT Licensed, free, self-hosted, and doesn't use cookies or fingerprinting. 

@avarner9 What do you think of Altcha?

**Comment by avarner9** [comment]
Looks like a proof of work algorithm, I think that's a much better solution. Thanks for finding that.

(By the way, if anyone else is reading this looking for a workaround for hcaptcha: Hit the hcaptcha refresh icon until you get an "ornament" puzzle. That puzzle definitely isn't training an AI, because it's easy to programmatically generate those puzzles with their solution, so they wouldn't need any human labor for such a training system.)

**Comment by avarner9** [comment]
Compare to: https://en.wikipedia.org/wiki/Hashcash (a system for email messages to be not marked as spam -- it does not involve payments)
