### ISSUE TITLE
bug: Uncategorized channels are duplicated in the "Categories" section in server settings

### ISSUE THREAD

**Issue by Asudox** [revoltchat/frontend#283]
### What happened?

Uncategorized channels are duplicated in the "Categories" server settings. This is only true for the last channel in the hierarchy in the "Uncategorized" column. Adding another text or voice channel after the first one deduplicates the first one, duplicating the new one in the view and making the first one undraggable.

Steps to reproduce:

1. Go to "Categories" section in the server settings
2. Create a new text/voice channel in the "Uncategorized" column

**Comment by insertish** [comment]
revite is deprecated, frontend does not have this functionality yet
