### ISSUE TITLE
bug: white screen?

### ISSUE THREAD

**Issue by andriemc** [revoltchat/frontend#284]
### What happened?

I went to https://revolt.chat/app and it gave me a white screen.

I'm using Brave Browser on Windows 11 (any sort of adblock is disabled)
Here's a screenshot as well

![image](https://github.com/revoltchat/frontend/assets/72381315/7c64dff4-e2d7-4ee6-ac65-5bdd2083dbf5)

**Comment by Rexogamer** [comment]
You need to log in at https://revolt.chat/login first - however, the app *should* redirect you, so half bug/half missing feature.

**Comment by ghost** [comment]
> You need to log in at https://revolt.chat/login first - however, the app _should_ redirect you, so half bug/half missing feature.

Oh, Thank you!

**Comment by insertish** [comment]
Logic was changed.
