### ISSUE TITLE
issue: tooltips stay alive longer than they should

### ISSUE THREAD

**Issue by insertish** [revoltchat/frontend#292]
Can impair usage of client.

<img width="308" alt="Screenshot 2024-06-05 at 19 00 55" src="https://github.com/revoltchat/frontend/assets/38285861/db998abd-c6f0-4d47-9e4e-cefcb6017d48">

**Comment by insertish** [comment]
Some exploratory work on this:
- It seems, in some capacity, the tooltip element is 'lost'?
- Corresponding 'mouseleave' event (to 'mouseenter') always fires for the element w/ the tooltip. (in `floating.ts`)
  ![Image](https://github.com/user-attachments/assets/b962e614-d62d-4182-b50c-83b2cc1face0)
  ![Image](https://github.com/user-attachments/assets/e85531a5-d1af-4e95-8262-91db1585e5a6)

**Comment by sharkaccino** [comment]
testing this myself right now and so far this issue appears to be based on how fast you switch between elements with tooltips. for example (assuming you've joined multiple servers), if you rapidly move your cursor across your entire server list over and over, it'll create tons of empty elements in the #floating wrapper. if you do the same thing but much slower, it's largely okay.

not entirely sure what this means yet, if anything. but it might be a clue

**Comment by sharkaccino** [comment]
ok it seems like this isnt limited to tooltips. this issue affects all floating elements, including user cards.

user cards are a lot harder to trigger, but if i use an autoclicker program, the same issue happens.

**Comment by sharkaccino** [comment]
ive managed to narrow it down to this motion component in [FloatingManager.tsx](https://github.com/revoltchat/frontend/blob/main/packages/client/components/ui/components/floating/FloatingManager.tsx)

![Image](https://github.com/user-attachments/assets/98ad5b97-5fc5-49e8-b0ff-ae04479bbf0c)

if i remove the `<Motion>` and just leave the inner contents as-is...

![Image](https://github.com/user-attachments/assets/6ca3678e-2539-4359-8dfa-fe621b8577d2)

...it now suddenly works perfectly.

**Comment by insertish** [comment]
I don't think exit animations work anyways (and maybe shouldn't be included anyways) so I suppose adding CSS entry animations and getting rid of the Motion component will work fine.

**Comment by insertish** [comment]
Okay, removing the exit animation seems to fix it too! (not like it worked anyways)

**Comment by insertish** [comment]
thnx for the help debugging @JackDotJS
