### ISSUE TITLE
bug: "Information" text shows up as "text"

### ISSUE THREAD

**Issue by DynamityXD** [revoltchat/frontend#295]
### What happened?

What is happening:
![image](https://github.com/revoltchat/frontend/assets/174586801/5bb128bb-1ad9-4849-9137-10eb2191d141)

What should happen:
![image](https://github.com/revoltchat/frontend/assets/174586801/181dc769-32dc-4789-b4d4-3d3bab735348)

**Comment by sharkaccino** [comment]
since #305 was merged, i'm gonna go ahead and close this as completed.
