### ISSUE TITLE
bug: Sending a message automatically sends a duplicate of that message.

### ISSUE THREAD

**Issue by DynamityXD** [revoltchat/frontend#297]
### What happened?

When sending a message in the chat, it seems to duplicate the message.

[Screen recording 2024-07-03 22.16.20.webm](https://github.com/revoltchat/frontend/assets/174586801/e1d50678-d8ef-445a-9ad4-3813c0f9972c)

However, the duplicate can be easily removed by **reloading the page** and it doesn't affect the people who you are sending the message to. _(They do NOT see a duplicate.)_

**Comment by insertish** [comment]
This was fixed.
