### ISSUE TITLE
bug: Can't build - missing assets

### ISSUE THREAD

**Issue by Rushmore75** [revoltchat/frontend#299]
### What happened?

When trying to build in dev mode (using the README as a guide) the frontend crashes with
`import RevoltSvg from "../../public/assets/wordmark_wide_500px.svg?component-solid";` when trying to import it in `/packages/client/components/auth/src/AuthPage.tsx`
When trying to fix it by download the official assets the repo https://github.com/revoltchat/assets/ is missing, where are the assets stored now?

**Comment by Rushmore75** [comment]
It appears that `/packages/client/public/assets` is just missing `wordmark_wide_500px.svg`, when I put a dummy svg there the site loads without error

**Comment by Rexogamer** [comment]
it seems `wide.svg` is unused/afaik was originally used for this? see also https://github.com/upryzing/lavender/commit/9d7ed28d836067f06661c4c7ad2ca0037d5939ec
