### ISSUE TITLE
feat(server-list): show server name on hover

### ISSUE THREAD

**Issue by DeclanChidlow** [revoltchat/frontend#30]
### What do you want to see?

When hovering over a server in the far left pane the server's name is not displayed.

requires #60

**Comment by Rexogamer** [comment]
This was done in a5dd4a3a819cc23e48d678840dc971379c89dc94:
![image](https://user-images.githubusercontent.com/42586271/215002905-2bde8829-eea4-4f09-80c3-fb74a8910b9f.png)
