### ISSUE TITLE
bug: other server leave events kick current user out

### ISSUE THREAD

**Issue by insertish** [revoltchat/frontend#312]
### What happened?

title

**Comment by sharkaccino** [comment]
shouldn't this be on the revolt.js repo? or am i missing something

**Comment by insertish** [comment]
This is still the demonstrated behaviour in the client so I think it could be either-or repo.
Easier to track it under client development I think...

I think this might be related to https://github.com/revoltchat/revolt.js/issues/96, https://github.com/revoltchat/revolt.js/pull/105 too.
