### ISSUE TITLE
bug: Revolt bug pack lite

### ISSUE THREAD

**Issue by DjPandaZ** [revoltchat/frontend#315]
### What happened?

# Hello! There is all bugs what I found while using Revolt Chat
### VOICE SETTINGS[^1]
![Image](https://github.com/user-attachments/assets/502d6cf5-06a9-4f03-9845-f119f8ae9aaa)
- [x] There are we can connect and communicate
- [ ] We can setup other devices for this program and save it in variable
> [!NOTE]
> We wanna see the best of auidio quality for gaming! 

### CONNECTING TROUBLE[^2]
![Image](https://github.com/user-attachments/assets/8150d3a4-50bb-4f65-921d-29d9e6f05604)
- [x] We can connect to the voice channel
- [ ] We can connect to the voice channel the first time
- [ ] We can Deafen ears while connecting to the voice channel
- [ ] We can mute or unmute ourself
> [!IMPORTANT]
> When muting the headphones, the program for some reason thinks that I wanted to exit the voice channel. When I press the MUTE button, I am thrown out of the voice channel. Also, I can't work with the microphone volume

### New account reg... STRANGE LOGIC FOR TOP BAR[^3]
![Image](https://github.com/user-attachments/assets/526f1a28-5bd4-4eb5-be2b-08fa9ed15123)
![Image](https://github.com/user-attachments/assets/a3d6c3de-a8f0-488b-84ad-b6a9dc4a29be)
- [x] Looks good when we look at it in the menu
- [ ] Looks good when we look at it in the any settings (we don't even see the message - "New account registtrations are currentrly limited")
> [!IMPORTANT]
> I would like the program to remember that the top panel should be on top when we go to the settings menu. As I understand it, the top panel location variable is saved in the same place, regardless of the transition to the settings menu.

[^1]:Voice settings
[^2]:Connecting trouble
[^3]:Missing top bar location variable when we going to the settings

**Comment by sharkaccino** [comment]
please don't report multiple bugs in a single issue. this makes things much more difficult for us to keep track of.

also, these appear to be bugs related to revite. the repo you're looking for is here: https://github.com/revoltchat/revite. i could just transfer this issue, but given the circumstances, i think it would be more productive to instead open new, separate issues for each of the problems described here (assuming they haven't been reported already).
