### ISSUE TITLE
feature request:

### ISSUE THREAD

**Issue by xlaas** [revoltchat/frontend#322]
### What do you want to see?

я не могу включить микрофон хотя даю разрешение на использование что за хуйня  вот мой никнейм Xlaas#7233

**Comment by sharkaccino** [comment]
we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. however, voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

(машинный перевод):
мы хорошо осведомлены о различных проблемах, связанных с существующей системой голосового чата. как говорится на баннере, текущая система может не работать. однако в настоящее время голосовой чат переписывается с нуля. проблему отслеживания можно найти здесь: https://github.com/revoltchat/backend/issues/313
