### ISSUE TITLE
bug: Can't use microphone

### ISSUE THREAD

**Issue by Tahinli** [revoltchat/frontend#324]
### What happened?

Hi, 

I can't unmute myself and it shows some errors

![Image](https://github.com/user-attachments/assets/ae59ebac-bfbe-4970-a5f5-0ec5ac692592)

**Comment by sharkaccino** [comment]
we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. however, voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313
