### ISSUE TITLE
bug: Unable to enable Sound settings on PC

### ISSUE THREAD

**Issue by KVenom** [revoltchat/frontend#325]
### What happened?

What I expected — for them to work out of the box, like Teamspeak or, you know,  DISCORD.

What heppened? — it keeps asking for permissions. On PC. On Win10. I can understand that whole BS on Mobile or on WIN11. But this is WIn 10.

Never had to do any "permissions to access audio settings" bs on any other communicator. Please, remove this mobile BS on PC version, por favor.

![Image](https://github.com/user-attachments/assets/cd3dd464-7a81-4176-9bb0-f3814b893228)

Doesn't matter if I press the damn button, it still reverts back if I switch tabs for a moment.

**Comment by marat19992288** [comment]
У меня и у друга тоже самое

**Comment by sharkaccino** [comment]
we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. however, voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313
