### ISSUE TITLE
feature request: alternate endpoint for self-hosted installations

### ISSUE THREAD

**Issue by kmeaw** [revoltchat/frontend#327]
### What do you want to see?

Currently there is no way to log into an alternate endpoint, such as a self-hosted installation, other than using that installation's web client.
It would be nice to have some dialog that presents a custom endpoint form, like Element (Matrix client) does for homeservers, to override the default $VITE_API_URL.

**Comment by sharkaccino** [comment]
im not sure this is relevant? my understanding is that any self-hosted revolt instance is supposed to also provide their own instance of the frontend client, and the client at revolt.chat/app is intended for use with the official revolt instance only.

**Comment by DeclanChidlow** [comment]
> my understanding is that any self-hosted revolt instance is supposed to also provide their own instance of the frontend client

This is correct. We have no intention to allow accessing instances from another instance's deployment of the frontend. It is up to each self-hosted instance to deploy the front-end themselves.
