### ISSUE TITLE
feature request: displaying people in the voice channel

### ISSUE THREAD

**Issue by maestroTW** [revoltchat/frontend#328]
### What do you want to see?

**What do you want to see?**
Displaying people in the voice channel before you log in to it

Like this:
![Image](https://github.com/user-attachments/assets/b1b26613-6f38-4edf-802d-f7abffc03865)

**Comment by sharkaccino** [comment]
to my knowledge, this is already planned, but i can't find the specific issue/thread mentioning it yet. will leave this open until then

**Comment by sharkaccino** [comment]
finally found it. it was buried in the middle of the todo list in the tracking issue for the voice overhaul lol https://github.com/revoltchat/backend/issues/313

closing as duplicate
