### ISSUE TITLE
How to start voice communication?

### ISSUE THREAD

**Issue by kocerar** [revoltchat/frontend#329]
I created a separate virtual machine, installed vortex, added a .env file with a config for working with the revolt server, but it seems that the config file needs to be loaded somehow differently, because it does not load and voice communication does not start. Tell me, what am I doing wrong?
I get this warnings when server starts:
```rust
warning: unused return value of `must_use` that must be used
  --> src/util/variables.rs:67:5
   |
67 |     format!("{}", *WS_URL);
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: this warning originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `must_use` that must be used
  --> src/util/variables.rs:68:5
   |
68 |     format!("{}", *MANAGE_TOKEN);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `must_use` that must be used
  --> src/util/variables.rs:70:5
   |
70 |     format!("{}", RTC_IPS.len());
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `vortex` (bin "vortex") generated 3 warnings
```

**Comment by sharkaccino** [comment]
this is not the repo for this.

from https://github.com/revoltchat/vortex/issues/23#issuecomment-1113594595:
> Vortex will not be receiving any documentation in the near future since the developer behind it is currently not available. More over there's a lot of things which we want to rebuild or completely replace and we don't have the time spare to currently handle this.
> 
> I would recommend not self-hosting Vortex until it's received a proper overhaul
