### ISSUE TITLE
feature request: filter out members without ViewChannel permissions in member sidebar

### ISSUE THREAD

**Issue by amycatgirl** [revoltchat/frontend#334]
### What do you want to see?

Currently, all members are shown inside every channel, regardless of whether they actually have permission to actually view the channel. As the title suggests, I think that they should be hidden from the sidebar to better reflect a channel's view permissions, similar to how competing chat platforms handle this scenario.

**Comment by sharkaccino** [comment]
couldve sworn there was an open issue for this already, but otherwise 100% yes pls

**Comment by insertish** [comment]
Already implemented?

**Comment by amycatgirl** [comment]
Closing the issue as apparently this has been implemented already

I should've checked that before opening the issue in the first place, oops!
