### ISSUE TITLE
bug: Captcha Broken

### ISSUE THREAD

**Issue by thecow275** [revoltchat/frontend#336]
### What happened?

I keep getting InternalError on registration attempt and CaptchaFailed in network console whenever I try to register on app.revolt.chat, also getting cross site cookie errors

**Comment by thecow275** [comment]
oh also I am using Firefox 132.0.2 if that helps any and the network error in the network tab also has a status of 500

**Comment by thecow275** [comment]
![Image](https://github.com/user-attachments/assets/4898170d-0f32-4398-8dde-dbe0d42a911e)

**Comment by Lanwara** [comment]
Can confirm I am having the same problem when trying to register. I am using Windows 11 and Firefox 132.0 (Zen Browser 1.0.1-a.19)

![Screenshot of 500 Captcha failed response](https://github.com/user-attachments/assets/33f184eb-857f-4d1e-a264-5d43d463a17b)

**Comment by thecow275** [comment]
actually this should porbably be moved to https://github.com/revoltchat/backend/issues/388 instead since it is a backend issue as far as I see

**Comment by thecow275** [comment]
this seems to now have been fixed on the backend
