### ISSUE TITLE
feat: server badges

### ISSUE THREAD

**Issue by DeclanChidlow** [revoltchat/frontend#36]
### What do you want to see?

Servers don't currently have their badges. e.g 'Official Server'.

**Comment by KernowAnna** [comment]
![Image](https://github.com/revoltchat/frontend/assets/136554285/998625f2-77d2-4316-b0e7-6f82dd346514)

**Comment by Rexogamer** [comment]
We already have badges (i.e. the Verified/Official Server badges) on Revite - this issue is about adding them to the new client

**Comment by KernowAnna** [comment]
ah okay

**Comment by krestenlaust** [comment]
> ah okay

Looks nice anyhow :)
