### ISSUE TITLE
bug: unread messages notification doesn't disappear

### ISSUE THREAD

**Issue by DeclanChidlow** [revoltchat/frontend#53]
### What happened?

In the messages sidebar the exclamation point doesn't disappear after reading messages or sending messages.

**Comment by SupertigerDev** [comment]
Seems like this is just not implemented yet 😅

**Comment by DeclanChidlow** [comment]
Fair enough. I've not had a chance to get elbow deep in the code yet so I honestly don't know what is a bug and what isn't implemented.

**Comment by insertish** [comment]
Closed in ff7d3fd321a73dbd0251dc21000b070e7032c80f.
