### ISSUE TITLE
feat: channel description

### ISSUE THREAD

**Issue by DeclanChidlow** [revoltchat/frontend#54]
### What do you want to see?

Channel description in top bar should be added.

**Comment by sharkaccino** [comment]
is this still relevant? i can see channel descriptions just fine, unless there's something else i'm missing 
![image](https://github.com/revoltchat/frontend/assets/31686191/0a8ff4bb-cf13-4dd8-a7b3-75cdf7edf3f2)

**Comment by Rexogamer** [comment]
minus some design polish (which applies to the app more widely), this looks complete to me so I'll close this - @insertish if I've missed anything feel free to reopen.
